use if-then-else

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -61,13 +61,13 @@ script:
     git reset --hard
     bumpversion --new-version=0.$TRAVIS_JOB_NUMBER minor
     echo "Host github.com" >> ~/.ssh/config
-    { { # try
-    openssl aes-256-cbc -K $encrypted_a70d5afca909_key -iv $encrypted_a70d5afca909_iv -in publish-key.enc -out ~/.ssh/publish-key -d
-    } && {
+    if openssl aes-256-cbc -K $encrypted_a70d5afca909_key -iv $encrypted_a70d5afca909_iv -in publish-key.enc -out ~/.ssh/publish-key -d
+    then
     chmod u=rw,og= ~/.ssh/publish-key
     echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config
     git push git@github.com:ionelmc/python-nameless.git -f HEAD:${PR}test-$ENV
-    } } || echo "openssl failed with $?"
+    else echo "openssl failed with $?"
+    fi
   - echo Done.
 
 notifications:
