do not git push if openssl failed

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -47,13 +47,6 @@ install:
 script:
   - git config --global user.email "you@example.com"
   - git config --global user.name "Your Name"
-  - |
-    { # try
-    openssl aes-256-cbc -K $encrypted_a70d5afca909_key -iv $encrypted_a70d5afca909_iv -in publish-key.enc -out ~/.ssh/publish-key -d
-    chmod u=rw,og= ~/.ssh/publish-key
-    echo "Host github.com" >> ~/.ssh/config
-    echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config
-    } || echo "openssl failed with $?"
   - git --version
   - ci/test.sh $ENV
   - |
@@ -67,7 +60,14 @@ script:
     git diff
     git reset --hard
     bumpversion --new-version=0.$TRAVIS_JOB_NUMBER minor
+    echo "Host github.com" >> ~/.ssh/config
+    { { # try
+    openssl aes-256-cbc -K $encrypted_a70d5afca909_key -iv $encrypted_a70d5afca909_iv -in publish-key.enc -out ~/.ssh/publish-key -d
+    } && {
+    chmod u=rw,og= ~/.ssh/publish-key
+    echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config
     git push git@github.com:ionelmc/python-nameless.git -f HEAD:${PR}test-$ENV
+    } } || echo "openssl failed with $?"
   - echo Done.
 
 notifications:
